#cloud-config
write_files:
  - content: |
      [SERVICE]
          Flush         1
          Log_File      /var/log/fluentbit.log
          Log_Level     error
          Daemon        off
          Parsers_File  /fluent-bit/etc/parsers.conf

      [FILTER]
          Name parser
          Match worker.logs
          Key_Name log
          Parser app_log_parser
          Reserve_Data On

      [INPUT]
          Name              forward
          Listen            0.0.0.0
          Port              24224
          Buffer_Chunk_Size 1M
          Buffer_Max_Size   6M

      [OUTPUT]
          Name            yc-logging
          Match           *
          group_id        e23k26epdqq33gaep71b
          message_key     text
          level_key       severity
          default_level   INFO
          authorization   instance-service-account
    path: /etc/fluentbit/fluentbit.conf
  - content: |
      [PARSER]
          Name   app_log_parser
          Format regex
          Regex  ^\[(?<severity>.*)\] (?<text>.*)$
    path: /etc/fluentbit/parsers.conf

ssh_pwauth: no
users:
  - name: avtrokhachev
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh-authorized-keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC5Go2XuzVPCeNdDBL7fK+pjmW8lbCMhdhmHHzDGcLARPJq/bRi8TIyE+s4abcMRU9TAnu92Yb0B+VnAqvHihSmz1Md25EYN08zRhHp74157PvqrOK4j6T/vBR8s0u6MD500fNx0ZAElrwPP7dfQP+63VJpsjLdnBL2oM6FwJJBZ0p5qECl1+/GtV6lt9mOMsewKySrc5eOEcRZTk5y11YbtImhxyEBNmB+mGaK8kUpZeVEFDMGk3EvzCzVm+6JGDsIXkQ3KT966tcBrKLGngGjJNDTvmNQIc3Zd+i5gU23+rgwD50d86r+WBbT0zURmfG7rQAC1RdPW7W/89s723M89K5AoZLV/i6/XQ/y2ekC9v3uPVS9BPiNwQjg+uLUkurXkGTFUPj6Uv3GurqSdm0sdl8ueYBh0tywRzbqrIZVttLFxVXKV2TBC/lZ096B31KbUz+LwU74ViMYCybU8u3ty6VskD0I3sn/avlyUqqEZPBOLRVOYt2zLvxp4p+svrE= avtrokhachev@i106040781"

runcmd:
  - export DEBIAN_FRONTEND=noninteractive
  - sudo apt-get update -y
  - sudo apt-get install -y docker.io
  - sudo systemctl start docker
  - sudo docker pull cr.yandex/crpoqe2ki2gq5j0p88mp/steam_items_worker:latest
  - docker run -d -v /etc/fluentbit/fluentbit.conf:/fluent-bit/etc/fluent-bit.conf -v /etc/fluentbit/parsers.conf:/fluent-bit/etc/parsers.conf --name fluentbit -p 24224:24224 -p 24224:24224/udp -e YC_GROUP_ID=e23k26epdqq33gaep71b cr.yandex/yc/fluent-bit-plugin-yandex:v1.0.3-fluent-bit-1.8.6
  - sleep 30
  - docker run --log-driver fluentd --log-opt fluentd-address=localhost:24224 --log-opt tag=worker.logs cr.yandex/crpoqe2ki2gq5j0p88mp/steam_items_worker:latest
